services:
  - type: worker
    name: social-media-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py --scheduler
    envVars:
      - key: ENCRYPTION_KEY
        generateValue: true